version: "3.9"

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d:ro
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    ports:
      - "5173:5173"
    depends_on:
      - db

  web:
    container_name: laravel_web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    container_name: laravel_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    container_name: laravel_phpmyadm
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-laravel}
      PMA_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - db

volumes:
  mysql-data:
